export type VocabWord = {
  word: string
  partOfSpeech: string
  definition: string
  example: string
  synonyms: string[]
  remember: string
}

export const VOCAB_WORDS: VocabWord[] = [
  {
    word: "Quixotic",
    partOfSpeech: "adjective",
    definition: "Chasing ideals that are noble but wildly impractical.",
    example: "His quixotic plan to end traffic by giving everyone a bicycle went nowhere.",
    synonyms: ["idealistic", "impractical", "starry-eyed"],
    remember: "From Don Quixote, who charged windmills thinking they were giants.",
  },
  {
    word: "Acerbic",
    partOfSpeech: "adjective",
    definition: "Sharp and biting, especially in speech or humor.",
    example: "Her acerbic review of the play left the director fuming.",
    synonyms: ["caustic", "sardonic", "tart"],
    remember: "Sounds like acid — words with a burn in them.",
  },
  {
    word: "Axiomatic",
    partOfSpeech: "adjective",
    definition: "So obviously true that it needs no proof.",
    example: "It is axiomatic that people work harder when they feel respected.",
    synonyms: ["self-evident", "unquestionable", "given"],
    remember: "An axiom in math is a truth you start from, never one you prove.",
  },
  {
    word: "Contrition",
    partOfSpeech: "noun",
    definition: "Genuine remorse for having done something wrong.",
    example: "His apology carried real contrition, not just a wish to end the argument.",
    synonyms: ["remorse", "penitence", "repentance"],
    remember: "From conterere, to grind down — a heart worn down by regret.",
  },
  {
    word: "Taciturn",
    partOfSpeech: "adjective",
    definition: "Naturally quiet; not inclined to talk much.",
    example: "Her taciturn father spoke maybe ten words over dinner.",
    synonyms: ["reserved", "reticent", "laconic"],
    remember: "Tacit means unspoken; taciturn is a person who stays that way.",
  },
  {
    word: "Demagoguery",
    partOfSpeech: "noun",
    definition: "Political appeals that stir up fear and prejudice instead of reason.",
    example: "The speech was pure demagoguery, blaming outsiders for every local problem.",
    synonyms: ["rabble-rousing", "fearmongering", "grandstanding"],
    remember: "Demos (people) + agogos (leader): driving the crowd by its emotions.",
  },
  {
    word: "Implacable",
    partOfSpeech: "adjective",
    definition: "Impossible to calm, satisfy, or win over.",
    example: "She met implacable opposition from the board no matter how she revised it.",
    synonyms: ["relentless", "unyielding", "inexorable"],
    remember: "Im- (not) + placate. You cannot placate them.",
  },
  {
    word: "Acceding",
    partOfSpeech: "verb",
    definition: "Agreeing to a request or demand, often after first resisting.",
    example: "After weeks of pressure, he finally acceded to their terms.",
    synonyms: ["consenting", "yielding", "assenting"],
    remember: "Ac- + cede, to give way — you give way to what is asked.",
  },
  {
    word: "Abstruse",
    partOfSpeech: "adjective",
    definition: "Hard to understand because it is deep or obscure.",
    example: "The paper's abstruse notation lost everyone outside the field.",
    synonyms: ["obscure", "arcane", "recondite"],
    remember: "Abs + trudere, pushed away — held out of easy reach.",
  },
  {
    word: "Adroit",
    partOfSpeech: "adjective",
    definition: "Skillful and clever, especially at handling tricky situations.",
    example: "She was adroit at defusing tension before it turned into a fight.",
    synonyms: ["deft", "adept", "dexterous"],
    remember: "French à droit, to the right — the skilled hand.",
  },
  {
    word: "Ambivalent",
    partOfSpeech: "adjective",
    definition: "Holding mixed or conflicting feelings about something.",
    example: "He felt ambivalent about the promotion: more money, but far more travel.",
    synonyms: ["conflicted", "torn", "of two minds"],
    remember: "Ambi- (both) + valence (pull). Both feelings tug at once.",
  },
  {
    word: "Ameliorate",
    partOfSpeech: "verb",
    definition: "To make a bad situation better.",
    example: "The new policy did little to ameliorate the housing shortage.",
    synonyms: ["improve", "alleviate", "ease"],
    remember: "Melior is Latin for better — to better something.",
  },
  {
    word: "Anodyne",
    partOfSpeech: "adjective",
    definition: "So bland and inoffensive that it provokes no reaction at all.",
    example: "The company issued an anodyne statement that said nothing.",
    synonyms: ["bland", "innocuous", "unobjectionable"],
    remember: "Originally a painkiller: it soothes, and it is dull.",
  },
  {
    word: "Antipathy",
    partOfSpeech: "noun",
    definition: "A deep, settled dislike of someone or something.",
    example: "There was clear antipathy between the two department heads.",
    synonyms: ["aversion", "animosity", "hostility"],
    remember: "Anti- (against) + pathos (feeling): feeling set against.",
  },
  {
    word: "Apocryphal",
    partOfSpeech: "adjective",
    definition: "Widely repeated but probably not true.",
    example: "The story about him quitting on the spot is almost certainly apocryphal.",
    synonyms: ["unverified", "spurious", "legendary"],
    remember: "The Apocrypha: texts whose authenticity was always disputed.",
  },
  {
    word: "Apposite",
    partOfSpeech: "adjective",
    definition: "Strikingly appropriate to the point at hand.",
    example: "She chose an apposite quotation to close the eulogy.",
    synonyms: ["apt", "fitting", "pertinent"],
    remember: "Looks like opposite, means the reverse of off-topic — it fits.",
  },
  {
    word: "Assiduous",
    partOfSpeech: "adjective",
    definition: "Showing careful and persistent effort.",
    example: "His assiduous note-taking saved the project when the server crashed.",
    synonyms: ["diligent", "industrious", "sedulous"],
    remember: "From sedere, to sit — you sit at the task until it is done.",
  },
  {
    word: "Austere",
    partOfSpeech: "adjective",
    definition: "Severely plain and without comfort or decoration; also stern in manner.",
    example: "The room was austere: a bed, a chair, and nothing else.",
    synonyms: ["spartan", "stark", "ascetic"],
    remember: "It sounds as stern as it is. An austere budget strips everything out.",
  },
  {
    word: "Bellicose",
    partOfSpeech: "adjective",
    definition: "Eager to fight; aggressive in tone or posture.",
    example: "His bellicose tone turned a small disagreement into a standoff.",
    synonyms: ["belligerent", "combative", "pugnacious"],
    remember: "Bellum is Latin for war — the root inside rebel too.",
  },
  {
    word: "Bombastic",
    partOfSpeech: "adjective",
    definition: "Inflated and pompous in language, with little substance behind it.",
    example: "The speech was bombastic, all thunder and no argument.",
    synonyms: ["grandiloquent", "pompous", "overblown"],
    remember: "Sounds like bombs going off: much noise, little content.",
  },
  {
    word: "Cacophony",
    partOfSpeech: "noun",
    definition: "A harsh, jarring mixture of sounds.",
    example: "A cacophony of horns rose from the blocked intersection.",
    synonyms: ["din", "discord", "racket"],
    remember: "Caco- (bad) + phony (sound): bad sound.",
  },
  {
    word: "Capricious",
    partOfSpeech: "adjective",
    definition: "Changing suddenly and without good reason.",
    example: "The weather here is capricious in April.",
    synonyms: ["fickle", "mercurial", "whimsical"],
    remember: "A caper is a sudden leap — capricious moods leap around.",
  },
  {
    word: "Cogent",
    partOfSpeech: "adjective",
    definition: "Clear and convincing, with real force of reason.",
    example: "She made a cogent case for delaying the launch.",
    synonyms: ["persuasive", "compelling", "forceful"],
    remember: "From cogere, to compel — a cogent argument drives you.",
  },
  {
    word: "Conflagration",
    partOfSpeech: "noun",
    definition: "A large, destructive fire; by extension, a spreading conflict.",
    example: "The conflagration consumed four city blocks before dawn.",
    synonyms: ["blaze", "inferno", "firestorm"],
    remember: "Con- + flagrare, to burn — the root hiding in flagrant.",
  },
  {
    word: "Conundrum",
    partOfSpeech: "noun",
    definition: "A difficult problem with no easy answer.",
    example: "Scheduling everyone across three time zones was a real conundrum.",
    synonyms: ["dilemma", "quandary", "puzzle"],
    remember: "Sounds like a drum you keep beating with no result.",
  },
  {
    word: "Corollary",
    partOfSpeech: "noun",
    definition: "Something that follows naturally from what came before.",
    example: "Higher rents are a corollary of the tech boom.",
    synonyms: ["consequence", "upshot", "outgrowth"],
    remember: "In geometry, the free result you get once a theorem is proved.",
  },
  {
    word: "Deference",
    partOfSpeech: "noun",
    definition: "Respectful yielding to someone else's judgment or wishes.",
    example: "Out of deference to her seniority, he withdrew his objection.",
    synonyms: ["respect", "regard", "esteem"],
    remember: "De- + ferre, to carry — you carry your own view out of the way.",
  },
  {
    word: "Didactic",
    partOfSpeech: "adjective",
    definition: "Intended to teach, sometimes in a heavy-handed or preachy way.",
    example: "The novel is beautiful until the last chapter, which turns didactic.",
    synonyms: ["instructive", "moralizing", "preachy"],
    remember: "Same root as didactics, the science of teaching.",
  },
  {
    word: "Diffident",
    partOfSpeech: "adjective",
    definition: "Lacking confidence; shy about putting oneself forward.",
    example: "He was diffident in meetings even though he knew the material best.",
    synonyms: ["timid", "self-effacing", "hesitant"],
    remember: "The opposite of confident — the trust in oneself is missing.",
  },
  {
    word: "Disparate",
    partOfSpeech: "adjective",
    definition: "Fundamentally different; not really comparable.",
    example: "The report tries to link disparate findings into a single theory.",
    synonyms: ["dissimilar", "divergent", "unrelated"],
    remember: "Related to disparity — things held far apart.",
  },
  {
    word: "Eclectic",
    partOfSpeech: "adjective",
    definition: "Drawn from a wide variety of sources or styles.",
    example: "Her bookshelf is eclectic: physics, poetry, and cookbooks side by side.",
    synonyms: ["varied", "wide-ranging", "diverse"],
    remember: "From eklegein, to pick out — you pick the best from everywhere.",
  },
  {
    word: "Elide",
    partOfSpeech: "verb",
    definition: "To leave out or slur over, often merging things by skipping a distinction.",
    example: "The summary elides the differences between the two proposals.",
    synonyms: ["omit", "skip", "gloss over"],
    remember: "In speech we elide sounds: going to becomes gonna.",
  },
  {
    word: "Elliptical",
    partOfSpeech: "adjective",
    definition: "So compressed or indirect that much of the meaning is left implied.",
    example: "His elliptical answers made the interview hard to follow.",
    synonyms: ["cryptic", "oblique", "terse"],
    remember: "An ellipsis (…) marks exactly what has been left out.",
  },
  {
    word: "Empirical",
    partOfSpeech: "adjective",
    definition: "Based on observation or experiment rather than theory.",
    example: "There is no empirical support for the claim yet.",
    synonyms: ["observed", "evidence-based", "experimental"],
    remember: "Empirical evidence comes from experience — same opening sound.",
  },
  {
    word: "Enervate",
    partOfSpeech: "verb",
    definition: "To drain of energy or vitality.",
    example: "The heat enervated everyone by mid-afternoon.",
    synonyms: ["exhaust", "sap", "debilitate"],
    remember: "E- (out) + nervus (sinew): the nerve taken out of you.",
  },
  {
    word: "Ephemeral",
    partOfSpeech: "adjective",
    definition: "Lasting a very short time.",
    example: "Fame online is ephemeral.",
    synonyms: ["fleeting", "transient", "short-lived"],
    remember: "Epi- + hemera (day): lasting about a day, like a mayfly.",
  },
  {
    word: "Equanimity",
    partOfSpeech: "noun",
    definition: "Calm, even-tempered composure, especially under strain.",
    example: "She received the bad news with surprising equanimity.",
    synonyms: ["composure", "poise", "serenity"],
    remember: "Equal + animus (mind): an even mind.",
  },
  {
    word: "Esoteric",
    partOfSpeech: "adjective",
    definition: "Understood by only a small group with specialized knowledge.",
    example: "The debate turned esoteric fast.",
    synonyms: ["arcane", "specialized", "obscure"],
    remember: "Eso- means within: knowledge kept inside the inner circle.",
  },
  {
    word: "Exculpate",
    partOfSpeech: "verb",
    definition: "To clear someone of blame or guilt.",
    example: "The footage exculpated the driver entirely.",
    synonyms: ["absolve", "exonerate", "acquit"],
    remember: "Ex- (out) + culpa (blame): the blame taken out.",
  },
  {
    word: "Exigent",
    partOfSpeech: "adjective",
    definition: "Urgent and demanding immediate attention.",
    example: "Only exigent circumstances justify skipping the review.",
    synonyms: ["pressing", "urgent", "critical"],
    remember: "An exigency is an emergency — same root, same hurry.",
  },
  {
    word: "Fastidious",
    partOfSpeech: "adjective",
    definition: "Very attentive to detail and hard to please.",
    example: "He is fastidious about how the data is labeled.",
    synonyms: ["meticulous", "punctilious", "exacting"],
    remember: "A fastidious person finds fault fast.",
  },
  {
    word: "Fatuous",
    partOfSpeech: "adjective",
    definition: "Silly and self-satisfied; foolish in a smug way.",
    example: "He offered a fatuous grin and no explanation.",
    synonyms: ["inane", "vacuous", "asinine"],
    remember: "Rhymes with vacuous and means much the same.",
  },
  {
    word: "Germane",
    partOfSpeech: "adjective",
    definition: "Relevant to the matter being discussed.",
    example: "That's interesting, but it isn't germane to the budget question.",
    synonyms: ["relevant", "pertinent", "applicable"],
    remember: "Once meant having the same parents — closely related to the topic.",
  },
  {
    word: "Hegemony",
    partOfSpeech: "noun",
    definition: "Dominance of one group, nation, or company over others.",
    example: "The company's hegemony over search shaped the whole industry.",
    synonyms: ["dominance", "supremacy", "ascendancy"],
    remember: "A hegemon is the leader — the one who leads by sheer weight.",
  },
  {
    word: "Iconoclast",
    partOfSpeech: "noun",
    definition: "Someone who attacks cherished beliefs or institutions.",
    example: "She built a career as an iconoclast in a conservative field.",
    synonyms: ["maverick", "dissenter", "rebel"],
    remember: "Literally an image-breaker: icon + klastes.",
  },
  {
    word: "Inchoate",
    partOfSpeech: "adjective",
    definition: "Just begun and not yet fully formed.",
    example: "He had an inchoate sense that something was wrong.",
    synonyms: ["nascent", "rudimentary", "unformed"],
    remember: "Inchoate ideas have not hatched yet.",
  },
  {
    word: "Indelible",
    partOfSpeech: "adjective",
    definition: "Impossible to remove, erase, or forget.",
    example: "The trip left an indelible impression on her.",
    synonyms: ["permanent", "lasting", "ineradicable"],
    remember: "In- (not) + delible (erasable). Think indelible ink.",
  },
  {
    word: "Ineffable",
    partOfSpeech: "adjective",
    definition: "Too great or intense to be put into words.",
    example: "There was an ineffable quality to the light that evening.",
    synonyms: ["inexpressible", "indescribable", "unutterable"],
    remember: "In- (not) + effable (speakable): it cannot be spoken.",
  },
  {
    word: "Ineluctable",
    partOfSpeech: "adjective",
    definition: "Impossible to avoid or escape.",
    example: "Aging is ineluctable.",
    synonyms: ["inescapable", "inevitable", "unavoidable"],
    remember: "In- + eluctari, to struggle out: you cannot wrestle free.",
  },
  {
    word: "Inscrutable",
    partOfSpeech: "adjective",
    definition: "Impossible to read or interpret.",
    example: "His inscrutable expression gave nothing away.",
    synonyms: ["enigmatic", "unreadable", "impenetrable"],
    remember: "You cannot scrutinize it — no amount of looking helps.",
  },
  {
    word: "Intimation",
    partOfSpeech: "noun",
    definition: "A subtle hint or indirect suggestion.",
    example: "There was an intimation in her email that she might leave.",
    synonyms: ["hint", "inkling", "suggestion"],
    remember: "To intimate something is to hint at it; this is the noun.",
  },
  {
    word: "Laconic",
    partOfSpeech: "adjective",
    definition: "Using very few words.",
    example: "His laconic “fine” ended the conversation.",
    synonyms: ["terse", "concise", "curt"],
    remember: "From Laconia (Sparta), whose people were famous for blunt brevity.",
  },
  {
    word: "Magnanimous",
    partOfSpeech: "adjective",
    definition: "Generous and forgiving, especially toward a rival.",
    example: "She was magnanimous in victory, praising the team she beat.",
    synonyms: ["generous", "gracious", "big-hearted"],
    remember: "Magna (great) + animus (spirit): great-souled.",
  },
  {
    word: "Obdurate",
    partOfSpeech: "adjective",
    definition: "Stubbornly refusing to change one's mind.",
    example: "The landlord remained obdurate about the repairs.",
    synonyms: ["stubborn", "unyielding", "intransigent"],
    remember: "Ob- + durus (hard): hardened against you.",
  },
  {
    word: "Ostensible",
    partOfSpeech: "adjective",
    definition: "Stated as the reason, though probably not the real one.",
    example: "The ostensible purpose of the trip was research.",
    synonyms: ["apparent", "supposed", "professed"],
    remember: "From ostendere, to display: what is shown, not what is true.",
  },
  {
    word: "Parsimonious",
    partOfSpeech: "adjective",
    definition: "Extremely unwilling to spend money or give anything away.",
    example: "The parsimonious budget left no room for training.",
    synonyms: ["stingy", "miserly", "penny-pinching"],
    remember: "Parsimony is thrift carried well past sensible.",
  },
  {
    word: "Perspicacious",
    partOfSpeech: "adjective",
    definition: "Quick to notice and understand what others miss.",
    example: "A perspicacious reader will spot the contradiction on page two.",
    synonyms: ["astute", "shrewd", "discerning"],
    remember: "Perspicere, to see through — sharp-sighted about people and ideas.",
  },
  {
    word: "Polemic",
    partOfSpeech: "noun",
    definition: "A forceful written or spoken attack on a position.",
    example: "The essay is less an analysis than a polemic.",
    synonyms: ["diatribe", "tirade", "screed"],
    remember: "Polemos is Greek for war: a war fought in words.",
  },
  {
    word: "Circumspect",
    partOfSpeech: "adjective",
    definition: "Careful to weigh consequences before acting or speaking.",
    example: "She was circumspect about what she put in writing.",
    synonyms: ["cautious", "prudent", "wary"],
    remember: "Circum (around) + spect (look): looking all around before moving.",
  },
  {
    word: "Dispassionate",
    partOfSpeech: "adjective",
    definition: "Free of emotion or bias; coolly objective.",
    example: "The review needs a dispassionate reader, not a friend.",
    synonyms: ["impartial", "objective", "detached"],
    remember: "Dis- (without) + passion: without heat.",
  },
  {
    word: "Evanescent",
    partOfSpeech: "adjective",
    definition: "Fading quickly, vanishing almost as it appears.",
    example: "The evanescent smell of rain on hot pavement.",
    synonyms: ["fleeting", "transient", "ephemeral"],
    remember: "Same root as vanish: evanescere.",
  },
  {
    word: "Fortuitous",
    partOfSpeech: "adjective",
    definition: "Happening by chance, often in a lucky way.",
    example: "Their meeting was entirely fortuitous.",
    synonyms: ["chance", "accidental", "serendipitous"],
    remember: "Fortuna, the goddess of chance.",
  },
  {
    word: "Intransigent",
    partOfSpeech: "adjective",
    definition: "Refusing to compromise at all.",
    example: "Both sides were intransigent, so the talks collapsed.",
    synonyms: ["uncompromising", "inflexible", "obdurate"],
    remember: "In- (not) + transigere, to come to an agreement.",
  },
  {
    word: "Judicious",
    partOfSpeech: "adjective",
    definition: "Showing good judgment; sensible and well considered.",
    example: "A judicious use of color makes the chart readable.",
    synonyms: ["prudent", "sensible", "considered"],
    remember: "Same root as judge: judgment applied well.",
  },
  {
    word: "Loquacious",
    partOfSpeech: "adjective",
    definition: "Very talkative.",
    example: "Our loquacious guide filled every silence.",
    synonyms: ["talkative", "garrulous", "voluble"],
    remember: "Loqui, to speak — the root in eloquent and soliloquy.",
  },
  {
    word: "Mendacious",
    partOfSpeech: "adjective",
    definition: "Habitually dishonest; given to lying.",
    example: "The report called the testimony mendacious.",
    synonyms: ["untruthful", "deceitful", "duplicitous"],
    remember: "Mendax is Latin for liar.",
  },
  {
    word: "Nebulous",
    partOfSpeech: "adjective",
    definition: "Vague and lacking clear shape or definition.",
    example: "The plan was nebulous: big goals, no steps.",
    synonyms: ["vague", "hazy", "indistinct"],
    remember: "A nebula is a cloud of gas — no clear edges anywhere.",
  },
  {
    word: "Obsequious",
    partOfSpeech: "adjective",
    definition: "Excessively eager to please or obey.",
    example: "The obsequious host agreed with everything the critic said.",
    synonyms: ["fawning", "servile", "sycophantic"],
    remember: "Ob- + sequi, to follow: following someone around far too closely.",
  },
  {
    word: "Pedantic",
    partOfSpeech: "adjective",
    definition: "Overly concerned with minor rules and details.",
    example: "It's pedantic to correct someone's grammar mid-crisis.",
    synonyms: ["nitpicking", "fussy", "hairsplitting"],
    remember: "A pedant makes a display of small learning.",
  },
  {
    word: "Perfunctory",
    partOfSpeech: "adjective",
    definition: "Done as a routine duty, with no real care or interest.",
    example: "He gave the document a perfunctory glance and signed it.",
    synonyms: ["cursory", "mechanical", "halfhearted"],
    remember: "Per- + fungi, to perform: just going through the motions.",
  },
  {
    word: "Pernicious",
    partOfSpeech: "adjective",
    definition: "Causing serious harm, especially gradually and quietly.",
    example: "The pernicious effect of the rumor took months to surface.",
    synonyms: ["insidious", "harmful", "destructive"],
    remember: "Per- + nex (death): deadly, and working slowly.",
  },
  {
    word: "Precarious",
    partOfSpeech: "adjective",
    definition: "Unstable and likely to fail, fall, or collapse.",
    example: "The ladder was in a precarious position.",
    synonyms: ["unstable", "insecure", "perilous"],
    remember: "From prex, prayer — a situation you can only pray holds.",
  },
  {
    word: "Prodigious",
    partOfSpeech: "adjective",
    definition: "Impressively large, great, or powerful.",
    example: "She has a prodigious memory for names.",
    synonyms: ["enormous", "immense", "remarkable"],
    remember: "Related to prodigy — a scale that astonishes.",
  },
  {
    word: "Recalcitrant",
    partOfSpeech: "adjective",
    definition: "Stubbornly resisting authority, instruction, or control.",
    example: "The recalcitrant printer jammed again.",
    synonyms: ["defiant", "unruly", "obstinate"],
    remember: "Re- + calcitrare, to kick back — kicking against the spur.",
  },
  {
    word: "Redoubtable",
    partOfSpeech: "adjective",
    definition: "Formidable; commanding respect, often as an opponent.",
    example: "She's a redoubtable negotiator.",
    synonyms: ["formidable", "daunting", "imposing"],
    remember: "Someone you redoubt — fear and respect in the same breath.",
  },
  {
    word: "Reprobate",
    partOfSpeech: "noun",
    definition: "An unprincipled person, often described with some affection.",
    example: "The old reprobate charmed everyone anyway.",
    synonyms: ["scoundrel", "rogue", "rascal"],
    remember: "Re- + probare, to prove: someone who failed the test of character.",
  },
  {
    word: "Reticent",
    partOfSpeech: "adjective",
    definition: "Reluctant to speak or to reveal one's thoughts.",
    example: "He was reticent about why he had left the firm.",
    synonyms: ["reserved", "guarded", "tight-lipped"],
    remember: "Re- + tacere, to be silent: holding speech back.",
  },
  {
    word: "Sagacious",
    partOfSpeech: "adjective",
    definition: "Wise and shrewd in practical matters.",
    example: "Her sagacious advice saved us a year of work.",
    synonyms: ["wise", "astute", "discerning"],
    remember: "A sage is a wise person; sagacious is the adjective.",
  },
  {
    word: "Salient",
    partOfSpeech: "adjective",
    definition: "Standing out as the most noticeable or important.",
    example: "The salient point is that nobody checked the data.",
    synonyms: ["prominent", "key", "conspicuous"],
    remember: "From salire, to leap: the salient fact leaps out at you.",
  },
  {
    word: "Sanguine",
    partOfSpeech: "adjective",
    definition: "Cheerfully optimistic, especially in a difficult situation.",
    example: "She stayed sanguine about the outcome despite the setbacks.",
    synonyms: ["optimistic", "hopeful", "buoyant"],
    remember: "From the old sanguine humor — blood, thought to make one ruddy and cheerful.",
  },
  {
    word: "Solipsistic",
    partOfSpeech: "adjective",
    definition: "So absorbed in oneself that nothing else seems quite real.",
    example: "The memoir is solipsistic; other people barely appear.",
    synonyms: ["self-absorbed", "egocentric", "self-centered"],
    remember: "Solus (alone) + ipse (self): only the self exists.",
  },
  {
    word: "Stentorian",
    partOfSpeech: "adjective",
    definition: "Extremely loud and powerful, said of a voice.",
    example: "His stentorian laugh carried across the restaurant.",
    synonyms: ["booming", "thunderous", "resounding"],
    remember: "From Stentor in the Iliad, whose voice equalled fifty men.",
  },
  {
    word: "Supercilious",
    partOfSpeech: "adjective",
    definition: "Behaving as though superior to everyone around.",
    example: "The supercilious clerk barely looked up.",
    synonyms: ["haughty", "disdainful", "condescending"],
    remember: "Supercilium is the eyebrow — the look given down a raised brow.",
  },
  {
    word: "Tenuous",
    partOfSpeech: "adjective",
    definition: "Very weak or slight; barely holding together.",
    example: "The connection between the two events is tenuous.",
    synonyms: ["flimsy", "slight", "fragile"],
    remember: "Tenuis is Latin for thin — stretched thin.",
  },
  {
    word: "Truculent",
    partOfSpeech: "adjective",
    definition: "Aggressively hostile and looking for a fight.",
    example: "He turned truculent after the second round of questions.",
    synonyms: ["belligerent", "combative", "surly"],
    remember: "Sounds like a truck bearing down on you.",
  },
  {
    word: "Ubiquitous",
    partOfSpeech: "adjective",
    definition: "Seeming to be everywhere at once.",
    example: "Phones are ubiquitous now.",
    synonyms: ["omnipresent", "pervasive", "universal"],
    remember: "Ubique is Latin for everywhere.",
  },
  {
    word: "Unctuous",
    partOfSpeech: "adjective",
    definition: "Insincerely charming in an oily, ingratiating way.",
    example: "The unctuous salesman complimented everything in sight.",
    synonyms: ["oily", "smarmy", "ingratiating"],
    remember: "From unguere, to anoint with oil: greasy flattery.",
  },
  {
    word: "Vacillate",
    partOfSpeech: "verb",
    definition: "To waver back and forth between choices.",
    example: "He vacillated for weeks before accepting.",
    synonyms: ["waver", "dither", "equivocate"],
    remember: "The root means to sway physically — indecision you can see.",
  },
  {
    word: "Verisimilitude",
    partOfSpeech: "noun",
    definition: "The appearance of being true or real.",
    example: "The set design gives the film real verisimilitude.",
    synonyms: ["realism", "authenticity", "plausibility"],
    remember: "Veri (truth) + similis (like): like the truth.",
  },
  {
    word: "Vitriolic",
    partOfSpeech: "adjective",
    definition: "Savagely bitter and cruel in tone.",
    example: "The exchange turned vitriolic within minutes.",
    synonyms: ["caustic", "scathing", "venomous"],
    remember: "Vitriol is sulfuric acid — words that burn on contact.",
  },
  {
    word: "Wistful",
    partOfSpeech: "adjective",
    definition: "Quietly longing, usually with a touch of sadness.",
    example: "She gave a wistful look at her old house.",
    synonyms: ["nostalgic", "yearning", "melancholy"],
    remember: "Wist sounds like wish — a wish with regret attached.",
  },
  {
    word: "Zealous",
    partOfSpeech: "adjective",
    definition: "Deeply committed and energetic in pursuit of something.",
    example: "He is zealous about recycling.",
    synonyms: ["fervent", "ardent", "impassioned"],
    remember: "A zealot takes it to the extreme; zealous is the trait itself.",
  },
  {
    word: "Alacrity",
    partOfSpeech: "noun",
    definition: "Brisk and cheerful willingness to act.",
    example: "She accepted the invitation with alacrity.",
    synonyms: ["eagerness", "readiness", "promptness"],
    remember: "Alacer is Latin for lively: quick, and glad to go.",
  },
  {
    word: "Banal",
    partOfSpeech: "adjective",
    definition: "So ordinary and overused that it has become boring.",
    example: "The speech was full of banal advice.",
    synonyms: ["trite", "hackneyed", "clichéd"],
    remember: "Once meant open to everyone — common as dirt.",
  },
  {
    word: "Candid",
    partOfSpeech: "adjective",
    definition: "Honest and direct, even when that is awkward.",
    example: "Can I be candid? The design isn't working.",
    synonyms: ["frank", "forthright", "blunt"],
    remember: "A candid photo catches you unposed — no filter on it.",
  },
  {
    word: "Deleterious",
    partOfSpeech: "adjective",
    definition: "Causing harm or damage, often to health.",
    example: "Long shifts have a deleterious effect on judgment.",
    synonyms: ["harmful", "damaging", "injurious"],
    remember: "Deleterious things quietly delete your wellbeing.",
  },
  {
    word: "Eloquent",
    partOfSpeech: "adjective",
    definition: "Speaking or writing fluently and persuasively.",
    example: "Her eloquent closing won the room.",
    synonyms: ["articulate", "expressive", "fluent"],
    remember: "E- + loqui, to speak out — and to speak out well.",
  },
  {
    word: "Fractious",
    partOfSpeech: "adjective",
    definition: "Irritable and inclined to squabble.",
    example: "The committee grew fractious in its third hour.",
    synonyms: ["quarrelsome", "unruly", "testy"],
    remember: "Fractious groups fracture into arguments.",
  },
  {
    word: "Impetuous",
    partOfSpeech: "adjective",
    definition: "Acting suddenly on impulse, without thinking it through.",
    example: "An impetuous decision he regretted by morning.",
    synonyms: ["rash", "impulsive", "hasty"],
    remember: "Impetus is force — you rush forward carried by it.",
  },
  {
    word: "Juxtapose",
    partOfSpeech: "verb",
    definition: "To place things side by side, usually to show a contrast.",
    example: "The exhibit juxtaposes early sketches with the finished mural.",
    synonyms: ["contrast", "pair", "set side by side"],
    remember: "Juxta (beside) + pose (place): placed beside.",
  },
  {
    word: "Lucid",
    partOfSpeech: "adjective",
    definition: "Clear and easy to understand; also clear-headed.",
    example: "A lucid explanation of a tangled subject.",
    synonyms: ["clear", "coherent", "intelligible"],
    remember: "Lux is light — lucid writing lets the light through.",
  },
  {
    word: "Nuance",
    partOfSpeech: "noun",
    definition: "A subtle difference in meaning, tone, or feeling.",
    example: "The translation misses the nuance of the original.",
    synonyms: ["subtlety", "shade", "gradation"],
    remember: "From nue, cloud: a faint shading of color.",
  },
  {
    word: "Pragmatic",
    partOfSpeech: "adjective",
    definition: "Focused on what actually works rather than on theory.",
    example: "A pragmatic fix now beats a perfect one next year.",
    synonyms: ["practical", "realistic", "hard-headed"],
    remember: "Pragma is Greek for deed — judged by what it does.",
  },
  {
    word: "Reify",
    partOfSpeech: "verb",
    definition: "To treat an abstract idea as if it were a concrete thing.",
    example: "The metric reifies engagement into a number that hides the real behavior.",
    synonyms: ["concretize", "objectify", "materialize"],
    remember: "Res is Latin for thing — to thing-ify an idea.",
  },
]

// Days elapsed in local time, so the word turns over at local midnight.
function dayNumber(date: Date): number {
  return Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000,
  )
}

// Stepping by a stride coprime with the list length visits every word exactly
// once before any repeat, so no history needs to be stored.
const STRIDE = 45

export function wordForDate(date: Date): VocabWord {
  const n = VOCAB_WORDS.length
  const index = ((dayNumber(date) * STRIDE) % n + n) % n
  return VOCAB_WORDS[index]
}
